### ISSUE TITLE
Download doesn't extract all the words

### ISSUE THREAD

**Issue by malinos** [nathanielove/English-words-pronunciation-mp3-audio-download#1]
Hello - 
thank you a lot for this code! I've releasied that this code doesn't extract all the 119376 due to the following case:
![image](https://user-images.githubusercontent.com/13124066/27040782-b6578c24-4f9a-11e7-9115-9cff389dcbea.png)

**(1288/119376) on/off switch**
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "<ipython-input-38-822937252833>", line 18, in run
    download_mp3(word, url, self.dir_path)
  File "<ipython-input-36-87d5fb6c5e7b>", line 4, in download_mp3
    with open(filename, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'download/on/off switch.mp3'

Kind regards,
AM

**Comment by malinos** [comment]
For sure it's not the best option, but will help:
1. to avoid download of the existing files in case of the 2nd run
2. solve the issue above
def download_mp3(word, url, dir_path):
	filename = os.path.join(dir_path, word + MP3_FILENAME_EXTENSION)
	filename = filename.replace("/", "")  ## Added
	if os.path.isfile(filename) == False: ## Added
		with open(filename, 'wb') as file:
			file.write(requests.get(url).content)

**Comment by nathanielove** [comment]
Actually this repository was not maintained in the past year so I'm not sure whether the links found last year still work now. I'll try getting some spare time to check it soon.

**Comment by yura-arab4uk** [comment]
Hi! This code worked with exceptions but when it had reached above 500 words program stopped working, so I changed one of the methods to catch and ignore exceptions and now it works fine: 
`def download_mp3(word, url, dir_path):
    filename = os.path.join(dir_path, word + MP3_FILENAME_EXTENSION)
    try:
        with open(filename, 'wb') as file:
            file.write(requests.get(url).content)
    except Exception:
        pass`

**Comment by yura-arab4uk** [comment]
Some files are corrupted though (
